Diagnose: output exit status from `rm ./yafu`

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -61,7 +61,15 @@ jobs:
         yafu_pid=$!
         wait ${rust_pid} || true
         echo "Rust program exited"
-        rm yafu # Prevent any more yafu processes from starting
+        
+        # Prevent any more yafu processes from starting
+        rm ./yafu
+        rm_yafu_status=$?
+        if [ ${rm_yafu_status} -eq 0 ]; then
+          echo "yafu deleted"
+        else
+          echo "rm ./yafu failed with status ${rm_yafu_status}"
+        fi
         yafus=$(ps -C yafu -o pid=)
         if [ "${yafus}" != "" ]; then
           echo "Canceling ${#yafus} unfinished yafu processes"
